# Site settings
title: The Maddest Bomber&#58; A Hearthstone Blog
email: kylebnazario@gmail.com
description: > # this means to ignore newlines until "baseurl:"
        Everything you need to know about Hearthstone news. Brought to 
        you by me, Kyle Nazario. Follow my blog for Hearthstone analysis, 
        news aggregation and reviews. I produce analysis and content for 
        people who care about the intricacies of the game. I want to
        hear from you- send me a letter! 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.maddestbomber.com" # the base hostname & protocol for your site
twitter_username: maddestblog
github_username:  kyle-n
facebook_username: knazario
linkedin_username: kylenazario
googleplus_username: +KyleNazario
email: kylebnazario@gmail.com
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"
permalink: /:year/:month/:day/:title.html

# Add Google Analytics tracking
analytics :
  provider : google
  google : 
      tracking_id : 'UA-67452206-1'

# Array builder
array: []

# Build settings
markdown: kramdown
safe : true
related_posts_max : 3

# Social settings
locale : en_us
timezone : America/New_York
icon : "{{ site.url }}/blog/assets/me.png"
author : 
   facebook : knazario
   twitter : kbn_le
   google_plus : KyleNazario
fb_admins : '1184042582'
fb_appid : 794821543963847
